# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='budgetline',
            name='spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='bookingaccount',
            name='budgetlines',
            field=models.ManyToManyField(to='budget.BudgetLine'),
        ),
    ]
