FROM python:3.14.2-alpine

ENV TZ=Europe/Stockholm

RUN pip install poetry

RUN apk --no-cache add build-base libpq libpq-dev py3-psycopg2 nginx

WORKDIR /app

COPY pyproject.toml poetry.lock ./

COPY . .

RUN poetry install

RUN ln -s staticfiles static # It seems like it sometimes only looks in staticfiles/ and other times only in static/

EXPOSE 8000

ENTRYPOINT ["/app/run.sh"]
