[supervisord]
nodaemon=true

[program:backend]
command=poetry run gunicorn cashflow.wsgi --bind=0.0.0.0:8000 -t 600 --log-file -
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:frontend]
command=bun run dev -- --host 0.0.0.0 --port 5173
directory=/app/frontend
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true

[program:nginx]
command=nginx -g "daemon off;"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
autorestart=true
