# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 14:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0018_expense_confirmed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('confirmed_at', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField()),
                ('verification', models.CharField(blank=True, max_length=7, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_line_id', models.IntegerField(default=0)),
                ('budget_line_name', models.TextField(blank=True)),
                ('cost_centre_name', models.TextField(blank=True)),
                ('cost_centre_id', models.IntegerField(default=0)),
                ('committee_name', models.TextField(blank=True)),
                ('committee_id', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('attest_date', models.DateField(blank=True, null=True)),
                ('attested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Profile')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice')),
            ],
        ),
    ]
