# Generated by Django 6.0.3 on 2026-04-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepart',
            name='budget_line',
        ),
        migrations.RemoveField(
            model_name='invoicepart',
            name='cost_centre',
        ),
        migrations.RemoveField(
            model_name='invoicepart',
            name='secondary_cost_centre',
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='gordian_budget_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
