# Generated by Django 6.0.1 on 2026-02-10 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepart',
            name='account',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='budget_line_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='cost_centre_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='secondary_cost_centre_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicepart',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='invoices.invoice'),
        ),
    ]
