# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20171224_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='verification',
            field=models.CharField(blank=True, default='', max_length=7),
            preserve_default=False,
        ),
    ]
