# Generated by Django 6.0.1 on 2026-02-14 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoicepart_account_invoicepart_budget_line_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepart',
            name='account',
        ),
        migrations.RemoveField(
            model_name='invoicepart',
            name='budget_line_id',
        ),
        migrations.RemoveField(
            model_name='invoicepart',
            name='cost_centre_id',
        ),
        migrations.RemoveField(
            model_name='invoicepart',
            name='secondary_cost_centre_id',
        ),
    ]
