# Generated by Django 6.0.3 on 2026-04-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoicepart_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepart',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', related_query_name='invoicepart', to='invoices.invoice'),
        ),
    ]
