# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_auto_20171225_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='file_is_original',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
