// App Actions

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const SET_APP_TITLE = 'SET_APP_TITLE';

// Expenses Actions

export const LOAD_EXPENSES = 'LOAD_EXPENSES';
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS';
export const LOAD_EXPENSES_FAIL = 'LOAD_EXPENSES_FAIL';

// Expense Actions

export const LOAD_EXPENSE = 'LOAD_EXPENSE';
export const LOAD_EXPENSE_SUCCESS = 'LOAD_EXPENSE_SUCCESS';
export const LOAD_EXPENSE_FAIL = 'LOAD_EXPENSE_FAIL';

export const LOAD_EXPENSE_COMMENTS = 'LOAD_EXPENSE_COMMENTS';
export const LOAD_EXPENSE_COMMENTS_SUCCESS = 'LOAD_EXPENSE_COMMENTS_SUCCESS';
export const LOAD_EXPENSE_COMMENTS_FAIL = 'LOAD_EXPENSE_COMMENTS_FAIL';

// Profile Actions

export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';
export const PROFILE_MODEL_CHANGE = 'PROFILE_MODEL_CHANGE';
export const PROFILE_SUBMIT = 'PROFILE_SUBMIT';
export const PROFILE_SUBMIT_SUCCESS = 'PROFILE_SUBMIT_SUCCESS';
export const PROFILE_SUBMIT_FAIL = 'PROFILE_SUBMIT_FAIL';

// New Expense

export const LOAD_COMMITTEES = 'LOAD_COMMITTEES';
export const LOAD_COMMITTEES_SUCCESS = 'LOAD_COMMITTEES_SUCCESS';
export const LOAD_COMMITTEES_FAIL = 'LOAD_COMMITTEES_FAIL';
export const LOAD_COST_CENTRES = 'LOAD_COST_CENTRES';
export const LOAD_COST_CENTRES_SUCCESS = 'LOAD_COST_CENTRES_SUCCESS';
export const LOAD_COST_CENTRES_FAIL = 'LOAD_COST_CENTRES_FAIL';
export const ADD_EXPENSE_PART = 'ADD_EXPENSE_PART';
export const NEW_EXPENSE_MODEL_CHANGE = 'NEW_EXPENSE_MODEL_CHANGE';
export const NEW_EXPENSE_SUBMIT = 'NEW_EXPENSE_SUBMIT';
export const NEW_EXPENSE_SUBMIT_SUCCESS = 'NEW_EXPENSE_SUBMIT_SUCCESS';
export const NEW_EXPENSE_SUBMIT_FAIL = 'NEW_EXPENSE_SUBMIT_FAIL';
export const RESET_NEW_EXPENSE = 'RESET_NEW_EXPENSE';
export const EXPENSE_UPLOAD= 'EXPENSE_UPLOAD';
export const EXPENSE_UPLOAD_SUCCESS = 'EXPENSE_UPLOAD_SUCCESS';
export const EXPENSE_UPLOAD_FAIL = 'EXPENSE_UPLOAD_FAIL';
