// App Actions

export const LOAD_USER = 'LOAD_USER';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL';
export const SET_APP_TITLE = 'SET_APP_TITLE';

// Expenses Actions

export const LOAD_EXPENSES = 'LOAD_EXPENSES';
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS';
export const LOAD_EXPENSES_FAIL = 'LOAD_EXPENSES_FAIL';

// Expense Actions

export const LOAD_EXPENSE = 'LOAD_EXPENSE';
export const LOAD_EXPENSE_SUCCESS = 'LOAD_EXPENSE_SUCCESS';
export const LOAD_EXPENSE_FAIL = 'LOAD_EXPENSE_FAIL';

export const LOAD_EXPENSE_COMMENTS = 'LOAD_EXPENSE_COMMENTS';
export const LOAD_EXPENSE_COMMENTS_SUCCESS = 'LOAD_EXPENSE_COMMENTS_SUCCESS';
export const LOAD_EXPENSE_COMMENTS_FAIL = 'LOAD_EXPENSE_COMMENTS_FAIL';

// Profile Actions
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_FAIL = 'LOAD_PROFILE_FAIL';
export const PROFILE_MODEL_CHANGE = 'PROFILE_MODEL_CHANGE';
export const PROFILE_SUBMIT = 'PROFILE_SUBMIT';
export const PROFILE_SUBMIT_SUCCESS = 'PROFILE_SUBMIT_SUCCESS';
export const PROFILE_SUBMIT_FAIL = 'PROFILE_SUBMIT_FAIL';