export const LOAD_EXPENSES = 'LOAD_EXPENSES';
export const LOAD_EXPENSES_SUCCESS = 'LOAD_EXPENSES_SUCCESS';
export const LOAD_EXPENSES_FAIL = 'LOAD_EXPENSES_FAIL';

export const LOAD_EXPENSE = 'LOAD_EXPENSE';
export const LOAD_EXPENSE_SUCCESS = 'LOAD_EXPENSE_SUCCESS';
export const LOAD_EXPENSE_FAIL = 'LOAD_EXPENSE_FAIL';

export const LOAD_EXPENSE_COMMENTS = 'LOAD_EXPENSE_COMMENTS';
export const LOAD_EXPENSE_COMMENTS_SUCCESS = 'LOAD_EXPENSE_COMMENTS_SUCCESS';
export const LOAD_EXPENSE_COMMENTS_FAIL = 'LOAD_EXPENSE_COMMENTS_FAIL';