# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2026-01-09 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('expenses', '0001_initial'), ('expenses', '0002_auto_20170313_1910'), ('expenses', '0003_auto_20170319_1134'), ('expenses', '0004_auto_20170708_2038'), ('expenses', '0005_auto_20170714_1003'), ('expenses', '0006_expense_created_date'), ('expenses', '0007_auto_20170717_2227'), ('expenses', '0008_remove_payment_amount'), ('expenses', '0009_auto_20170720_1612'), ('expenses', '0010_auto_20170803_0408'), ('expenses', '0011_auto_20170803_0432')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        # welcome to migration hell //hjalmar
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(blank=True, max_length=13)),
                ('sorting_number', models.CharField(blank=True, max_length=6)),
                ('bank_name', models.CharField(blank=True, max_length=30)),
                ('default_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.BankAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('firebase_instance_id', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CostCentre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Committee')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('description', models.TextField()),
                ('verification', models.CharField(blank=True, max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ExpensePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('attest_date', models.DateField(blank=True, null=True)),
                ('attested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Profile')),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.BudgetLine')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belonging_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense')),
                ('file', models.FileField(blank=True, null=True, storage='storages.backends.s3.S3Storage', upload_to='')),
                ('tempfile', models.FileField(default='file', storage='django.core.files.storage.FileSystemStorage', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.BankAccount')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer', to='expenses.Profile')),
                ('receiver', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='expenses.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='expensepart',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense'),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Payment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense'),
        ),
        migrations.AddField(
            model_name='budgetline',
            name='cost_centre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.CostCentre'),
        ),
        migrations.AlterField(
            model_name='expensepart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
