# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0003_auto_20170319_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Profile',
        ),
    ]
