# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-14 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0004_auto_20170708_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepart',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firebase_instance_id',
            field=models.TextField(blank=True),
        ),
    ]
