# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0006_expense_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
