# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0007_auto_20170717_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
    ]
