# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import queued_storage.backends


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20170720_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(storage=queued_storage.backends.QueuedStorage('django.core.files.storage.FileSystemStorage', 'expenses.custom_storages.MediaStorage'), upload_to=''),
        ),
    ]
