# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_auto_20170803_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='tempfile',
            field=models.FileField(default='file', storage='django.core.files.storage.FileSystemStorage', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, storage='expenses.custom_storages.MediaStorage', upload_to=''),
        ),
    ]
