# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('expenses', '0011_auto_20170803_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='tempfile',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
