# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_auto_20171101_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensepart',
            name='committee_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expensepart',
            name='cost_centre_id',
            field=models.IntegerField(default=0),
        ),
    ]
