# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_auto_20171101_1605'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='expensepart',
        #    name='budget_line_id',
        #),
    ]
