# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_expense_confirmed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='confirmed_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
