# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('expenses', '0018_expense_confirmed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='belonging_to',
            new_name='expense',
        ),
        migrations.AddField(
            model_name='file',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
