# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_auto_20171223_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.Expense'),
        ),
    ]
