# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_auto_20171224_2321'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='bankaccount',
                    table='base_bankaccount',
                ),
            ],
        ),
    ]
