# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2024-01-25 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_auto_20171224_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
    ]
