# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2024-09-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_auto_20240516_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
