# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2025-02-13 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0024_auto_20240516_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_flagged',
            field=models.NullBooleanField(),
        ),
    ]