# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20180817_0212'),
        ('base', '0001_initial'),
        ('expenses', '0024_auto_20180817_0212'),
        ('expenses', '0024_auto_20180817_0212'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='BankAccount',
                ),
            ],
        ),
    ]
