# Generated by Django 6.0.1 on 2026-01-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_expense_is_flagged'),
        ('expenses', '0025_fortnoxaccounts_fortnoxauthtoken'),
    ]

    operations = [
    ]
