# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_auto_20180817_0212'),
        ('expenses', '0023_auto_20180817_0212'),
    ]

    operations = [
    ]
