# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2024-10-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_fortnoxauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='FortnoxAccounts',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('URL', models.TextField()),
                ('Active', models.BooleanField()),
                ('BalanceBroughtForward', models.DecimalField(decimal_places=2, max_digits=9)),
                ('CostCenter', models.TextField()),
                ('CostCenterSettings', models.TextField()),
                ('Description', models.TextField()),
                ('Number', models.IntegerField(unique=True)),
                ('Project', models.TextField()),
                ('ProjectSettings', models.TextField()),
                ('SRU', models.IntegerField()),
                ('VATCode', models.TextField()),
                ('Year', models.IntegerField()),
            ],
        ),
    ]