# Generated by Django 6.0.1 on 2026-02-14 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_delete_fortnoxaccounts_delete_fortnoxauthtoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepart',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='expenses.expense'),
        ),
    ]
