# Generated by Django 6.0.3 on 2026-04-25 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_remove_bankaccount'),
        ('expenses', '0028_alter_expensepart_expense'),
    ]

    operations = [
    ]
