# Generated by Django 6.0.3 on 2026-04-25 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_merge_20260425_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensepart',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', related_query_name='expensepart', to='expenses.expense'),
        ),
    ]
