# Generated by Django 6.0.3 on 2026-05-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0030_alter_expensepart_expense"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="firebase_instance_id",
        ),
    ]
