"""
Django settings for cashflow project.

Generated by 'django-admin startproject' using Django 1.8.17.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

import os  # Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import re
import sys

import dj_database_url

# https://stackoverflow.com/questions/74875604/cannot-import-name-urlquote-from-django-utils-http
# Fix for broken "django-queued-storage" dependency
# TODO: Replace this dependency
# from urllib.parse import quote
# django.utils.http.urlquote = quote

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = BASE_DIR

# noinspection PyRedeclaration
AUTHENTICATION_BACKENDS = ['cashflow.dauth.DAuth']

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', '-01^^veefr*f_p=phew0w7ib37_738%=lwmp9n4bl_2*5^)vjy')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get('DEBUG', 'False') == "True")

GOOGLE_ANALYTICS_KEY = os.getenv('GOOGLE_ANALYTICS_KEY')

ALLOWED_HOSTS = ['*']

# CORS configuration
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [ "https://cashflow.datasektionen.se" ]

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'storages',
    'corsheaders',
    'widget_tweaks',
    'expenses',
    'invoices',
    'fortnox',
)

MIDDLEWARE = (
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'fortnox.FortnoxMiddleware',
)

ROOT_URLCONF = 'cashflow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'string_if_invalid': '%s',
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cashflow.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
if os.environ.get("DATABASE_URL"):  # Stuff for when running in Dokku.

    # Parse the DATABASE_URL env var.
    # First group is the (ql)? group, hence _
    _, USER, PASSWORD, HOST, PORT, NAME = re.match(
        r"^postgres(ql)?://(?P<username>.*?):(?P<password>.*?)@(?P<host>.*?):(?P<port>\d+)/(?P<db>.*?)$",
        os.environ.get("DATABASE_URL", "")).groups()

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': NAME,
            'USER': USER,
            'PASSWORD': PASSWORD,
            'HOST': HOST,
            'PORT': PORT,
        }
    }
else:

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'cashflow'),
            'USER': os.getenv('DB_USER', 'cashflow'),
            'PASSWORD': os.getenv('DB_PASS', 'cashflow'),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# noinspection PyRedeclaration
SESSION_COOKIE_AGE = 60 * 60 * 24 * 2  # Sessions expire after 2 days

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'sv-SE'

TIME_ZONE = 'Europe/Stockholm'

USE_I18N = True

USE_L10N = True

USE_TZ = True

OIDC_PROVIDER = os.getenv('OIDC_PROVIDER')
OIDC_ID = os.getenv('OIDC_ID')
OIDC_SECRET = os.getenv('OIDC_SECRET')
REDIRECT_URL = os.getenv('REDIRECT_URL')

BUDGET_URL = os.getenv('BUDGET_URL', 'https://budget.datasektionen.se')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATIC_URL = '/static/'

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (os.path.join(PROJECT_ROOT, 'staticfiles'),)

STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

MEDIAFILES_LOCATION = 'media'
if DEBUG:
    MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
    MEDIA_URL = '/media/'
else:
    AWS_STORAGE_BUCKET_NAME = os.getenv('S3_BUCKET_NAME', 'se.datasektionen.foo')
    AWS_ACCESS_KEY_ID = os.getenv('S3_ACCESS_KEY_ID', 'xxxxxxxxxxxxxxxxxxxx')
    AWS_SECRET_ACCESS_KEY = os.getenv('S3_SECRET_ACCESS_KEY', 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy')

    AWS_S3_HOST = os.getenv('S3_HOST', 's3.eu-central-1.amazonaws.com')
    AWS_S3_CUSTOM_DOMAIN = "{0}.s3.amazonaws.com".format(AWS_STORAGE_BUCKET_NAME)

    MEDIA_URL = "https://{0}/{1}/".format(AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location":  MEDIAFILES_LOCATION,
                "file_overwrite":  False,
            },
        },
        "staticfiles": STATICFILES_STORAGE
    }

SPAM_API_KEY = os.getenv('SPAM_API_KEY', 'Lobster Thermidor au Crevette with a Mornay sauce garnished with truffle '
                                         'pate, brandy and with a fried egg on top and spam.')
SPAM_URL = os.getenv('SPAM_URL', 'https://spam.datasektionen.se')

HIVE_URL = os.getenv('HIVE_URL', 'https://hive.datasektionen.se')
HIVE_SECRET = os.getenv('HIVE_SECRET', 'unset')

RFINGER_API_URL = os.getenv('RFINGER_API_URL', 'https://rfinger.datasektionen.se')
RFINGER_API_KEY = os.getenv('RFINGER_API_KEY', 'unset')

# Only send emails if set to true
SEND_EMAILS = (os.getenv('SEND_EMAILS', True) == 'True')

LOG_LEVEL = 'DEBUG' if DEBUG else 'INFO'
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {module}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': LOG_LEVEL,
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'fortnox': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        }
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
}


# Fortnox settings
FORTNOX_CLIENT_ID = os.getenv('FORTNOX_CLIENT_ID', 'client_id')
FORTNOX_CLIENT_SECRET = os.getenv('FORTNOX_CLIENT_SECRET')
FORTNOX_SCOPE = ['bookkeeping', 'companyinformation', 'settings', 'customer', 'profile']
# urlconf to redirect when requiring Fortnox authentication
FORTNOX_AUTH_REDIRECT = "fortnox-auth-get"
FORTNOX_CREDIT_ACCOUNT=1910
