# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_remove_expensepart_budget_line_id'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='expensepart',
        #    name='budget_line_id',
        #    field=models.IntegerField(default=0),
        #),
    ]
