# Generated by Django 6.0.3 on 2026-07-17 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0031_remove_profile_firebase_instance_id"),
        ("iso20022", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="pain_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="iso20022.paymentinitiationfile",
            ),
        ),
    ]
