# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_auto_20180817_0212'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='BankAccount',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.TextField()),
                    ],
                    options={
                        'indexes': [],
                    },
                ),
            ],
        ),
    ]
