# Generated by Django 6.0.1 on 2026-02-08 15:09
# with changes by Hjalmar Fjällborg

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [migrations.CreateModel(name='Account',
        fields=[('AccountID', models.AutoField(primary_key=True, serialize=False)),
            ('created_at', models.DateTimeField(auto_now_add=True)), ('URL', models.TextField()),
            ('Active', models.BooleanField()),
            ('BalanceBroughtForward', models.DecimalField(decimal_places=2, max_digits=9)),
            ('CostCenter', models.TextField()), ('CostCenterSettings', models.TextField()),
            ('Description', models.TextField()), ('Number', models.IntegerField()), ('Project', models.TextField()),
            ('ProjectSettings', models.TextField()), ('SRU', models.IntegerField()), ('VATCode', models.TextField()),
            ('Year', models.IntegerField()), ], ), migrations.CreateModel(name='APIUser', fields=[('user',
                                                                                                   models.OneToOneField(
                                                                                                       on_delete=django.db.models.deletion.CASCADE,
                                                                                                       primary_key=True,
                                                                                                       related_name='fortnox',
                                                                                                       serialize=False,
                                                                                                       to=settings.AUTH_USER_MODEL)),
        ('created_at', models.DateTimeField(auto_now_add=True)), ('access_token', models.TextField()),
        ('refresh_token', models.TextField()), ('name', models.TextField(default='Ture')), ], ), ]
