# Generated by Django 6.0.1 on 2026-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='name',
            field=models.TextField(),
        ),
    ]
