# Generated by Django 6.0.1 on 2026-01-28 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('fortnox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APITokens',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
