# Generated by Django 6.0.1 on 2026-02-23 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortnox', '0002_alter_apiuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
