name: Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Nomad
        uses: datasektionen/nomad-deploy@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nomad-token: ${{ secrets.NOMAD_TOKEN }}
          nomad-addr: ${{ vars.NOMAD_ADDR }}
